# .github/workflows/rebase-release.yml
name: Rebase preview branch onto main

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  rebase-release:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: set up git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: fetch all branches
        run: git fetch origin

      - name: checkout release branch
        run: git checkout preview

      - name: rebase release onto main
        run: git rebase origin/main

      - name: push rebased release
        run: git push origin preview --force-with-lease
